### ISSUE TITLE
This program is too cool 😎

### ISSUE THREAD

**Issue by vassilevsky** [tiredpixel/sidekiq-spy#14]
Hi 👻

I just discovered this gem (quite literally) and I am blown away by what I see in the console. I've been longing for this type of thing for a long time.

Great work! 💪

**Comment by pchaganti** [comment]
This is really really cool. Well done!

**Comment by tiredpixel** [comment]
@vassilevsky, @pchaganti, thank you both for your kind comments! :) -- tiredpixel
