### ISSUE TITLE
Does this work with Sidekiq4?

### ISSUE THREAD

**Issue by pchaganti** [tiredpixel/sidekiq-spy#15]
Anyone try this out with SK4? It runs but doesnt display any of the workers in the list.

**Comment by dskvr** [comment]
Bump

**Comment by tiredpixel** [comment]
@pchaganti, @dskvr, I personally haven't tried it with Sidekiq 4. There is outstanding https://github.com/tiredpixel/sidekiq-spy/pull/16 , but I haven't yet reviewed it. I'm not sure if it will still work with Sidekiq 3, for example. If more people are interested in this, perhaps they wouldn't mind assisting with testing that pull request on Sidekiq versions, both modern and previously-supported? -- Thanks, tiredpixel
